### ISSUE TITLE
コラボレーター招待

### ISSUE THREAD

**Issue by rnrnuraln** [hasesuns/PythonRobotics#1]
遅くなってしまい、大変申し訳ございません。
Pull requestを送ろうとしているのですが、権限がないためこのリポジトリにpushできません。SettingからCollaboratorに招待していただいてもよろしいでしょうか。多分それでpushできるようにナルト思います。よろしくお願いします。

**Comment by hasesuns** [comment]
ごめんなさい。夕方から私用で出かけてました>_<
僕もpushできなくて困ってたのですがCollaboratorに招待する必要があるんですね。
ご連絡ありがとうございました！
